version: '3'

services:
  web:
    build:
      context: .
    ports:
      - 8000:8000
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: 'test_platform'